// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1) {
  return window['go']['main']['App']['AddRule'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function GetActiveWindow() {
  return window['go']['main']['App']['GetActiveWindow']();
}

export function GetAvailableInputs() {
  return window['go']['main']['App']['GetAvailableInputs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentInput() {
  return window['go']['main']['App']['GetCurrentInput']();
}

export function GetLogStats() {
  return window['go']['main']['App']['GetLogStats']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetRunning(arg1) {
  return window['go']['main']['App']['SetRunning'](arg1);
}

export function SwitchInput(arg1) {
  return window['go']['main']['App']['SwitchInput'](arg1);
}

export function TestRule(arg1) {
  return window['go']['main']['App']['TestRule'](arg1);
}

export function UpdateRule(arg1, arg2) {
  return window['go']['main']['App']['UpdateRule'](arg1, arg2);
}
