// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AddRule(arg1:services.Rule):Promise<void>;

export function ClearLogs():Promise<void>;

export function DeleteRule(arg1:number):Promise<void>;

export function GetActiveWindow():Promise<services.WindowInfo>;

export function GetAvailableInputs():Promise<Array<services.InputMethod>>;

export function GetConfig():Promise<services.Config>;

export function GetCurrentInput():Promise<services.InputMethod>;

export function GetLogStats():Promise<Record<string, number>>;

export function GetRecentLogs(arg1:number):Promise<Array<services.LogEntry>>;

export function Greet(arg1:string):Promise<string>;

export function IsRunning():Promise<boolean>;

export function QuitApp():Promise<void>;

export function SaveConfig(arg1:services.Config):Promise<void>;

export function SetRunning(arg1:boolean):Promise<void>;

export function SwitchInput(arg1:string):Promise<void>;

export function TestRule(arg1:services.Rule):Promise<boolean>;

export function UpdateRule(arg1:number,arg2:services.Rule):Promise<void>;
